# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20170223_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furrurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
