# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20170224_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furrurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
